import './globals.css';
import type { Metadata } from 'next';
import LayoutWrapper from './layerWrapper';

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Jost:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-sans antialiased">
        {/* Client logic lives inside this */}
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
